
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var a;a||(a=typeof Module !== 'undefined' ? Module : {});var q,r;a.ready=new Promise(function(b,d){q=b;r=d});var u={},w;for(w in a)a.hasOwnProperty(w)&&(u[w]=a[w]);var x="";"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src);_scriptDir&&(x=_scriptDir);0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="";var y=a.printErr||console.warn.bind(console);for(w in u)u.hasOwnProperty(w)&&(a[w]=u[w]);u=null;var z;a.wasmBinary&&(z=a.wasmBinary);
var noExitRuntime=a.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var B,C=!1;function D(b){var d=a["_"+b];d||A("Assertion failed: Cannot call unknown function "+(b+", make sure it is exported"));return d}
function E(b,d,h,n){var e={string:function(c){var m=0;if(null!==c&&void 0!==c&&0!==c){var l=(c.length<<2)+1;m=F(l);var g=m,f=H;if(0<l){l=g+l-1;for(var t=0;t<c.length;++t){var k=c.charCodeAt(t);if(55296<=k&&57343>=k){var ba=c.charCodeAt(++t);k=65536+((k&1023)<<10)|ba&1023}if(127>=k){if(g>=l)break;f[g++]=k}else{if(2047>=k){if(g+1>=l)break;f[g++]=192|k>>6}else{if(65535>=k){if(g+2>=l)break;f[g++]=224|k>>12}else{if(g+3>=l)break;f[g++]=240|k>>18;f[g++]=128|k>>12&63}f[g++]=128|k>>6&63}f[g++]=128|k&63}}f[g]=
0}}return m},array:function(c){var m=F(c.length);I.set(c,m);return m}},p=D(b),G=[];b=0;if(n)for(var v=0;v<n.length;v++){var R=e[h[v]];R?(0===b&&(b=J()),G[v]=R(n[v])):G[v]=n[v]}h=p.apply(null,G);h=function(c){if("string"===d)if(c){for(var m=H,l=c+NaN,g=c;m[g]&&!(g>=l);)++g;if(16<g-c&&m.subarray&&K)c=K.decode(m.subarray(c,g));else{for(l="";c<g;){var f=m[c++];if(f&128){var t=m[c++]&63;if(192==(f&224))l+=String.fromCharCode((f&31)<<6|t);else{var k=m[c++]&63;f=224==(f&240)?(f&15)<<12|t<<6|k:(f&7)<<18|
t<<12|k<<6|m[c++]&63;65536>f?l+=String.fromCharCode(f):(f-=65536,l+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else l+=String.fromCharCode(f)}c=l}}else c="";else c="boolean"===d?!!c:c;return c}(h);0!==b&&L(b);return h}var K="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,I,H,M,N=[],O=[],P=[];function aa(){var b=a.preRun.shift();N.unshift(b)}var Q=0,S=null,T=null;a.preloadedImages={};a.preloadedAudios={};
function A(b){if(a.onAbort)a.onAbort(b);y(b);C=!0;b=new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");r(b);throw b;}function U(){return V.startsWith("data:application/octet-stream;base64,")}var V="zstd.wasm";if(!U()){var W=V;V=a.locateFile?a.locateFile(W,x):x+W}function ca(){var b=V;try{if(b==V&&z)return new Uint8Array(z);throw"both async and sync fetching of the wasm failed";}catch(d){A(d)}}
function da(){return z||"function"!==typeof fetch?Promise.resolve().then(function(){return ca()}):fetch(V,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+V+"'";return b.arrayBuffer()}).catch(function(){return ca()})}function X(b){for(;0<b.length;){var d=b.shift();if("function"==typeof d)d(a);else{var h=d.s;"number"===typeof h?void 0===d.o?M.get(h)():M.get(h)(d.o):h(void 0===d.o?null:d.o)}}}var ea={a:function(){A("OOM")},b:function(){}};
(function(){function b(e){a.asm=e.exports;B=a.asm.c;e=B.buffer;a.HEAP8=I=new Int8Array(e);a.HEAP16=new Int16Array(e);a.HEAP32=new Int32Array(e);a.HEAPU8=H=new Uint8Array(e);a.HEAPU16=new Uint16Array(e);a.HEAPU32=new Uint32Array(e);a.HEAPF32=new Float32Array(e);a.HEAPF64=new Float64Array(e);M=a.asm.m;O.unshift(a.asm.d);Q--;a.monitorRunDependencies&&a.monitorRunDependencies(Q);0==Q&&(null!==S&&(clearInterval(S),S=null),T&&(e=T,T=null,e()))}function d(e){b(e.instance)}function h(e){return da().then(function(p){return WebAssembly.instantiate(p,
n)}).then(e,function(p){y("failed to asynchronously prepare wasm: "+p);A(p)})}var n={a:ea};Q++;a.monitorRunDependencies&&a.monitorRunDependencies(Q);if(a.instantiateWasm)try{return a.instantiateWasm(n,b)}catch(e){return y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||U()||"function"!==typeof fetch?h(d):fetch(V,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,n).then(d,function(p){y("wasm streaming compile failed: "+
p);y("falling back to ArrayBuffer instantiation");return h(d)})})})().catch(r);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.d).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.e).apply(null,arguments)};a._free=function(){return(a._free=a.asm.f).apply(null,arguments)};a._ZSTD_isError=function(){return(a._ZSTD_isError=a.asm.g).apply(null,arguments)};a._ZSTD_getFrameContentSize=function(){return(a._ZSTD_getFrameContentSize=a.asm.h).apply(null,arguments)};
a._ZSTD_decompress=function(){return(a._ZSTD_decompress=a.asm.i).apply(null,arguments)};var J=a.stackSave=function(){return(J=a.stackSave=a.asm.j).apply(null,arguments)},L=a.stackRestore=function(){return(L=a.stackRestore=a.asm.k).apply(null,arguments)},F=a.stackAlloc=function(){return(F=a.stackAlloc=a.asm.l).apply(null,arguments)};a.ccall=E;a.cwrap=function(b,d,h,n){h=h||[];var e=h.every(function(p){return"number"===p});return"string"!==d&&e&&!n?D(b):function(){return E(b,d,h,arguments,n)}};var Y;
T=function fa(){Y||Z();Y||(T=fa)};
function Z(){function b(){if(!Y&&(Y=!0,a.calledRun=!0,!C)){X(O);q(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();P.unshift(d)}X(P)}}if(!(0<Q)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)aa();X(N);0<Q||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=Z;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Z();


  return Module.ready
}
);
})();
export default Module;