
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var a;a||(a=typeof Module !== 'undefined' ? Module : {});var q,r;a.ready=new Promise(function(b,c){q=b;r=c});var u={},w;for(w in a)a.hasOwnProperty(w)&&(u[w]=a[w]);var x="";"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src);_scriptDir&&(x=_scriptDir);0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="";var y=a.printErr||console.warn.bind(console);for(w in u)u.hasOwnProperty(w)&&(a[w]=u[w]);u=null;var z;a.wasmBinary&&(z=a.wasmBinary);
var noExitRuntime=a.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var B,C=!1;function D(b){var c=a["_"+b];c||A("Assertion failed: Cannot call unknown function "+(b+", make sure it is exported"));return c}
function E(b,c,e,g){var k={string:function(d){var n=0;if(null!==d&&void 0!==d&&0!==d){var m=(d.length<<2)+1;n=F(m);var h=n,f=G;if(0<m){m=h+m-1;for(var t=0;t<d.length;++t){var l=d.charCodeAt(t);if(55296<=l&&57343>=l){var da=d.charCodeAt(++t);l=65536+((l&1023)<<10)|da&1023}if(127>=l){if(h>=m)break;f[h++]=l}else{if(2047>=l){if(h+1>=m)break;f[h++]=192|l>>6}else{if(65535>=l){if(h+2>=m)break;f[h++]=224|l>>12}else{if(h+3>=m)break;f[h++]=240|l>>18;f[h++]=128|l>>12&63}f[h++]=128|l>>6&63}f[h++]=128|l&63}}f[h]=
0}}return n},array:function(d){var n=F(d.length);I.set(d,n);return n}},p=D(b),H=[];b=0;if(g)for(var v=0;v<g.length;v++){var R=k[e[v]];R?(0===b&&(b=J()),H[v]=R(g[v])):H[v]=g[v]}e=p.apply(null,H);e=function(d){if("string"===c)if(d){for(var n=G,m=d+NaN,h=d;n[h]&&!(h>=m);)++h;if(16<h-d&&n.subarray&&K)d=K.decode(n.subarray(d,h));else{for(m="";d<h;){var f=n[d++];if(f&128){var t=n[d++]&63;if(192==(f&224))m+=String.fromCharCode((f&31)<<6|t);else{var l=n[d++]&63;f=224==(f&240)?(f&15)<<12|t<<6|l:(f&7)<<18|
t<<12|l<<6|n[d++]&63;65536>f?m+=String.fromCharCode(f):(f-=65536,m+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else m+=String.fromCharCode(f)}d=m}}else d="";else d="boolean"===c?!!d:d;return d}(e);0!==b&&L(b);return e}var K="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,M,I,G;
function N(){var b=B.buffer;M=b;a.HEAP8=I=new Int8Array(b);a.HEAP16=new Int16Array(b);a.HEAP32=new Int32Array(b);a.HEAPU8=G=new Uint8Array(b);a.HEAPU16=new Uint16Array(b);a.HEAPU32=new Uint32Array(b);a.HEAPF32=new Float32Array(b);a.HEAPF64=new Float64Array(b)}var O,P=[],Q=[],S=[];function aa(){var b=a.preRun.shift();P.unshift(b)}var T=0,U=null,V=null;a.preloadedImages={};a.preloadedAudios={};
function A(b){if(a.onAbort)a.onAbort(b);y(b);C=!0;b=new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");r(b);throw b;}function ba(){return W.startsWith("data:application/octet-stream;base64,")}var W="zstd.wasm";if(!ba()){var ca=W;W=a.locateFile?a.locateFile(ca,x):x+ca}function ea(){var b=W;try{if(b==W&&z)return new Uint8Array(z);throw"both async and sync fetching of the wasm failed";}catch(c){A(c)}}
function fa(){return z||"function"!==typeof fetch?Promise.resolve().then(function(){return ea()}):fetch(W,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+W+"'";return b.arrayBuffer()}).catch(function(){return ea()})}function X(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var e=c.s;"number"===typeof e?void 0===c.o?O.get(e)():O.get(e)(c.o):e(void 0===c.o?null:c.o)}}}
var ha={a:function(b){var c=G.length;b>>>=0;if(2147483648<b)return!1;for(var e=1;4>=e;e*=2){var g=c*(1+.2/e);g=Math.min(g,b+100663296);g=Math.max(b,g);0<g%65536&&(g+=65536-g%65536);a:{try{B.grow(Math.min(2147483648,g)-M.byteLength+65535>>>16);N();var k=1;break a}catch(p){}k=void 0}if(k)return!0}return!1},b:function(){}};
(function(){function b(k){a.asm=k.exports;B=a.asm.c;N();O=a.asm.m;Q.unshift(a.asm.d);T--;a.monitorRunDependencies&&a.monitorRunDependencies(T);0==T&&(null!==U&&(clearInterval(U),U=null),V&&(k=V,V=null,k()))}function c(k){b(k.instance)}function e(k){return fa().then(function(p){return WebAssembly.instantiate(p,g)}).then(k,function(p){y("failed to asynchronously prepare wasm: "+p);A(p)})}var g={a:ha};T++;a.monitorRunDependencies&&a.monitorRunDependencies(T);if(a.instantiateWasm)try{return a.instantiateWasm(g,
b)}catch(k){return y("Module.instantiateWasm callback failed with error: "+k),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||ba()||"function"!==typeof fetch?e(c):fetch(W,{credentials:"same-origin"}).then(function(k){return WebAssembly.instantiateStreaming(k,g).then(c,function(p){y("wasm streaming compile failed: "+p);y("falling back to ArrayBuffer instantiation");return e(c)})})})().catch(r);return{}})();
a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.d).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.e).apply(null,arguments)};a._free=function(){return(a._free=a.asm.f).apply(null,arguments)};a._ZSTD_isError=function(){return(a._ZSTD_isError=a.asm.g).apply(null,arguments)};a._ZSTD_getFrameContentSize=function(){return(a._ZSTD_getFrameContentSize=a.asm.h).apply(null,arguments)};a._ZSTD_decompress=function(){return(a._ZSTD_decompress=a.asm.i).apply(null,arguments)};
var J=a.stackSave=function(){return(J=a.stackSave=a.asm.j).apply(null,arguments)},L=a.stackRestore=function(){return(L=a.stackRestore=a.asm.k).apply(null,arguments)},F=a.stackAlloc=function(){return(F=a.stackAlloc=a.asm.l).apply(null,arguments)};a.ccall=E;a.cwrap=function(b,c,e,g){e=e||[];var k=e.every(function(p){return"number"===p});return"string"!==c&&k&&!g?D(b):function(){return E(b,c,e,arguments,g)}};var Y;V=function ia(){Y||Z();Y||(V=ia)};
function Z(){function b(){if(!Y&&(Y=!0,a.calledRun=!0,!C)){X(Q);q(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();S.unshift(c)}X(S)}}if(!(0<T)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)aa();X(P);0<T||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=Z;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Z();


  return Module.ready
}
);
})();
export default Module;